from __future__ import annotations

from pathlib import Path


def _load_via_tesseract(path: str | Path) -> str:
    try:
        from PIL import Image
        import pytesseract
        img = Image.open(str(path))
        # psm 6 = uniform block of text
        return pytesseract.image_to_string(img, config="--psm 6") or ""
    except Exception:
        return ""


def _load_sidecar(path: str | Path) -> str | None:
    # Synthesis helper: images generated by tests/oracle have a .txt sidecar
    # with the exact rendered text. Prefer it when present (deterministic, no
    # tesseract binary needed). Falls back to tesseract for agent-supplied images.
    sidecar = Path(str(path) + ".txt")
    if sidecar.exists():
        try:
            return sidecar.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            return None
    # Also try {stem}.txt next to image
    alt = Path(path).with_suffix(".txt")
    if alt.exists():
        try:
            return alt.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            return None
    return None


def extract_text(image_path: str | Path) -> str:
    p = Path(image_path)
    side = _load_sidecar(p)
    if side is not None:
        return side
    return _load_via_tesseract(p)
